name: Deployment
on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: ${{ secrets.PORT}}
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: | 
          echo "envs: ${{env.MONGODB_CLUSTER_ADDRESS}}"
          npm ci
      - name: Check env presence
        run: |
          [ -n "$MONGODB_CLUSTER_ADDRESS" ] && echo "cluster address present" || echo "cluster address missing"
          [ -n "$MONGODB_USERNAME" ] && echo "username present" || echo "username missing"
          [ -n "$MONGODB_PASSWORD" ] && echo "password present" || echo "password missing"
          [ -n "$PORT" ] && echo "port present" || echo "port missing"
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME}}"
          echo "env: ${{ env}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "..."
